[2022-08-22 17:05:03,754] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: hello_nifi.get_nifi_processor_task 2022-08-22T17:04:57.196396+00:00 [queued]>
[2022-08-22 17:05:03,759] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: hello_nifi.get_nifi_processor_task 2022-08-22T17:04:57.196396+00:00 [queued]>
[2022-08-22 17:05:03,759] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 17:05:03,760] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-22 17:05:03,760] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-22 17:05:03,768] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): get_nifi_processor_task> on 2022-08-22T17:04:57.196396+00:00
[2022-08-22 17:05:03,771] {{standard_task_runner.py:53}} INFO - Started process 1288 to run task
[2022-08-22 17:05:03,798] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: hello_nifi.get_nifi_processor_task 2022-08-22T17:04:57.196396+00:00 [running]> myairflow
[2022-08-22 17:05:03,804] {{logging_mixin.py:112}} INFO - Testing connection to NiFi...
[2022-08-22 17:05:03,807] {{logging_mixin.py:112}} INFO - [2022-08-22 17:05:03,806] {{base_hook.py:84}} INFO - Using connection to: id: mynifi_connection. Host: http://mynifi, Port: 8080, Schema: None, Login: None, Password: None, extra: None
[2022-08-22 17:05:03,807] {{logging_mixin.py:112}} INFO - Rest endpoint: http://mynifi:8080/nifi-api/processors/1462a26f-0000-0000-0000-35550911fe94
[2022-08-22 17:05:03,819] {{logging_mixin.py:112}} INFO - Response: <Response [404]>
[2022-08-22 17:05:03,819] {{taskinstance.py:1128}} ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/nifi_operator.py", line 30, in get_nifi_processor
    print(f"Processor JSON: {json.loads(response.content)}")
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-08-22 17:05:03,822] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=hello_nifi, task_id=get_nifi_processor_task, execution_date=20220822T170457, start_date=20220822T170503, end_date=20220822T170503
[2022-08-22 17:05:13,752] {{logging_mixin.py:112}} INFO - [2022-08-22 17:05:13,752] {{local_task_job.py:103}} INFO - Task exited with return code 1
